# Generated by Django 4.2.6 on 2023-10-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cash', models.IntegerField()),
                ('transferPayment', models.IntegerField()),
                ('delivery', models.IntegerField()),
            ],
        ),
    ]
