# Generated by Django 4.2.8 on 2023-12-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPerformance',
        ),
    ]
