# Generated by Django 4.2.6 on 2023-10-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(choices=[('0', 'สาขาพหลโยธิน 52'), ('1', 'สาขารังสิต 200 ปี'), ('2', 'สาขาม.รังสิต')], max_length=20),
        ),
    ]
