# Generated by Django 4.2.6 on 2023-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(choices=[('1', 'สาขาพหลโยธิน 52'), ('2', 'สาขาม.รังสิต'), ('3', 'สาขารังสิต 200 ปี')], max_length=20),
        ),
    ]
